number = int(input("Введите число : "))
print(type(number))
print(number)
word = input('Введите слово : ')
print(word)
print(type(word))
number_float = float(input(' Введите десятичную дробь : '))
print(type(number_float))
person = bool(input('Вы мужчина ? '))
print(person)
print(type(person))